/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controles.UsuarioControle;
import ferramentas.CaixaDeDialogo;
import ferramentas.Criptografia;
import modelos.CadastroUsuario;

/**
 *
 * @author Bruno Martini
 */
public class CadUsuarios extends javax.swing.JFrame {

    CadastroUsuario objUsuario;
    UsuarioControle objUsuarioControle;
    
    public CadUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnEncrypt = new javax.swing.JButton();
        btnDescrypt = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setText("Login:");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        btnIncluir.setText("INCLUIR");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnEncrypt.setText("Encrypt");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnDescrypt.setText("Decrypt");
        btnDescrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescryptActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));
        getContentPane().add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        btnLogin.setText("ACESSAR");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 100, 40));

        lblNivel.setText("Nível:");
        getContentPane().add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
        getContentPane().add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        try{
            boolean retorno;
            //validar os campos
            if(txtLogin.getText().trim().length() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um login corretamente", 'a');
                return;
            }
            if(txtNome.getText().trim().length() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome corretamente", 'a');
                return;
            }
            if(txtSenha.getText().trim().length() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe uma senha corretamente", 'a');
                return;
            }
            if(txtNivel.getText().trim().length() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nível corretamente", 'a');
                return;
            }
            
            objUsuario = new CadastroUsuario();
            objUsuario.setLogin(txtLogin.getText().trim());
            objUsuario.setNome(txtNome.getText().trim());
            objUsuario.setSenha(txtEntrada.getText().trim());
            objUsuario.setNivel(txtNivel.getText().trim());
            
            if(!lblId.getText().equals("ID")){
                objUsuario.setId_usuario(Integer.parseInt(lblId.getText()));
                objUsuarioControle = new UsuarioControle(objUsuario);
                retorno = objUsuarioControle.alterar();
            }else{
                objUsuarioControle = new UsuarioControle(objUsuario);
                retorno = objUsuarioControle.incluir();
            }
            
            if(retorno = true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Registro salvo");
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao tentar salvar");
            }
            
          

        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao tentar incluir");
            System.out.println("ERRO: " + ex.getMessage().toString());
        }
            
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // TODO add your handling code here:
        txtEntrada.setText(Criptografia.Encriptar(txtSenha.getText()));
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDescryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescryptActionPerformed
        // TODO add your handling code here:
         txtEntrada.setText(Criptografia.Decriptar(txtSenha.getText()));
    }//GEN-LAST:event_btnDescryptActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login tela_login = new Login();
        tela_login.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
