/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.Conexao;
import static banco.Conexao.con;
import static banco.Conexao.stmt;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martini
 */
public class EntradaSaida extends javax.swing.JFrame {

    /**
     * Creates new form EntradaSaida
     */
    public EntradaSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVeiculos = new javax.swing.JTable();
        lblOperacao = new javax.swing.JLabel();
        rbEntrada = new javax.swing.JRadioButton();
        rbSaida = new javax.swing.JRadioButton();
        btnProcessar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("VEÍCULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jtbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Veículo", "Estoque"
            }
        ));
        jScrollPane1.setViewportView(jtbVeiculos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 450, 130));

        lblOperacao.setText("Operação:");
        getContentPane().add(lblOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        rbEntrada.setText("Entrada");
        rbEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(rbEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        rbSaida.setText("Saída");
        rbSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(rbSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        lblQuantidade.setText("Quantidade:");
        getContentPane().add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEntradaActionPerformed

    private void rbSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSaidaActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        // TODO add your handling code here:
       int linha = jtbVeiculos.getSelectedRow();
        if (validarDados() && (linha >= 0)) {
            String sql = "";
            if (rbEntrada.isSelected()) {
                sql = "UPDATE veiculo SET quantidade=quantidade+? WHERE id_veiculo=?";                
            } else {
                sql = "UPDATE veiculo SET quantidade=quantidade-? WHERE id_veiculo=?";                                
            }
            
            try {
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, txtQuantidade.getText());
                stmt.setString(2, jtbVeiculos.getValueAt(linha, 0).toString());
                stmt.execute();
                stmt.close();
                mostrarDados();
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro! Verifique os campos.");
        }
        txtQuantidade.setText("");
        txtQuantidade.grabFocus();
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaSaida().setVisible(true);
            }
        });
    }
    
    public void setOperacao(int op) {
        if (op == 1) {
            rbEntrada.setSelected(true);
        } else {
            rbSaida.setSelected(true);
        }
    }
    
    private void mostrarDados() {
       try {
           PreparedStatement stmt = con.prepareStatement("SELECT * FROM veiculo");
           ResultSet rs = stmt.executeQuery();
           DefaultTableModel model = (DefaultTableModel) jtbVeiculos.getModel();
           model.setRowCount(0); // Limpar Tabela
           while (rs.next()) {
               Object linha[] = {rs.getString("id_veiculo"), rs.getString("nome"),
                                 rs.getString("quantidade")};
               model.addRow(linha);
           }   
           stmt.close();
       } catch (Exception e) {
           e.printStackTrace();
       }
    }
    
    private boolean validarDados() {
        if (txtQuantidade.getText().trim().length() == 0) {
            return false;
        }
        
        try {
            int quantidade = Integer.parseInt(txtQuantidade.getText());
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbVeiculos;
    private javax.swing.JLabel lblOperacao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
